// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsGCXiguP9jap1dx43TLw7crNMTqXAI-I',
    appId: '1:56218742073:web:162c34cbdda367b29f8ce8',
    messagingSenderId: '56218742073',
    projectId: 'musicappprojectt',
    authDomain: 'musicappprojectt.firebaseapp.com',
    storageBucket: 'musicappprojectt.firebasestorage.app',
    measurementId: 'G-9W3XHET1H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGcZ__KPhsaXDERKE5iD0Ezeg4u7VHJUg',
    appId: '1:56218742073:android:7b4fd93013c937859f8ce8',
    messagingSenderId: '56218742073',
    projectId: 'musicappprojectt',
    storageBucket: 'musicappprojectt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFtXR6KiGT75wUKP9QJcvLrjhaRcw6Avg',
    appId: '1:56218742073:ios:a0f0245f155801c19f8ce8',
    messagingSenderId: '56218742073',
    projectId: 'musicappprojectt',
    storageBucket: 'musicappprojectt.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFtXR6KiGT75wUKP9QJcvLrjhaRcw6Avg',
    appId: '1:56218742073:ios:a0f0245f155801c19f8ce8',
    messagingSenderId: '56218742073',
    projectId: 'musicappprojectt',
    storageBucket: 'musicappprojectt.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsGCXiguP9jap1dx43TLw7crNMTqXAI-I',
    appId: '1:56218742073:web:7e6eeb5ece0a654a9f8ce8',
    messagingSenderId: '56218742073',
    projectId: 'musicappprojectt',
    authDomain: 'musicappprojectt.firebaseapp.com',
    storageBucket: 'musicappprojectt.firebasestorage.app',
    measurementId: 'G-XZSRKEZVKM',
  );
}
